# Generated by Django 4.2.2 on 2023-06-24 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0003_typebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='dashbord.typebanner'),
            preserve_default=False,
        ),
    ]
