# Generated by Django 4.2.2 on 2023-06-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0004_banner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='dis',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
