# Generated by Django 4.2.2 on 2023-06-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0006_userinfo_delete_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profile',
            field=models.ImageField(blank=True, upload_to='usersProfile'),
        ),
    ]
