# Generated by Django 4.2.2 on 2023-06-25 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0007_userinfo_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user',
            new_name='info',
        ),
    ]
