# Generated by Django 4.2.2 on 2023-06-25 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0008_rename_user_userinfo_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='rubika',
            new_name='instagram',
        ),
    ]
