# Generated by Django 4.2.2 on 2023-06-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0012_remove_userinfo_info_userinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile',
            field=models.ImageField(default='user.jpg', upload_to='usersProfile'),
        ),
    ]
