# Generated by Django 4.2.2 on 2023-06-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0013_alter_userinfo_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='bio',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
