# Generated by Django 4.2.2 on 2023-06-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0014_userinfo_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile',
            field=models.ImageField(blank=True, default='user.jpg', upload_to='usersProfile'),
        ),
    ]
