# Generated by Django 4.2.2 on 2023-06-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0015_alter_userinfo_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=150)),
                ('user', models.CharField(max_length=150)),
            ],
        ),
    ]
