# Generated by Django 4.2.2 on 2023-06-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='clearer',
        ),
        migrations.RemoveField(
            model_name='category',
            name='lole',
        ),
        migrations.RemoveField(
            model_name='category',
            name='pomp',
        ),
        migrations.RemoveField(
            model_name='category',
            name='users',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
