# Generated by Django 4.2.2 on 2023-06-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_rename_img_item_img1_item_img2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img1',
            field=models.ImageField(upload_to='item_img'),
        ),
    ]
