# Generated by Django 4.2.2 on 2023-06-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(upload_to='categpry_img'),
        ),
    ]
