# Generated by Django 4.2.2 on 2023-06-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_item_likes_likeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='likeitem',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
