# Generated by Django 4.2.2 on 2023-06-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_alter_likeitem_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeitem',
            name='post',
        ),
        migrations.RemoveField(
            model_name='likeitem',
            name='relate',
        ),
        migrations.AddField(
            model_name='likeitem',
            name='post_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
