# Generated by Django 4.2.2 on 2023-06-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_remove_likeitem_post_remove_likeitem_relate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeitem',
            name='post_id',
            field=models.IntegerField(max_length=50),
        ),
    ]
