# Generated by Django 4.2.2 on 2023-06-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_alter_likeitem_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeitem',
            name='post_id',
            field=models.IntegerField(),
        ),
    ]
