# Generated by Django 4.2.2 on 2023-06-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_alter_likeitem_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='off',
            field=models.IntegerField(default=0),
        ),
    ]
